### ISSUE TITLE
ItemBindingDiffCallback관련 로직을 ListAdapter를 구현함으로써 해결

### ISSUE THREAD

**Issue by kimdohun0104** [Team-DA/Corona-Solution#45]
ListAdapter는 업데이트된 데이터만 RecyclerView에서 변경처리될 수 있도록 설계된 개념입니다.
현재 사용하고 있는 DiffUtil을 개념을 사용해 구현됩니다.

[문제가 되는 곳](https://github.com/KRMKGOLD/MaskLocationProject/blob/a718ca44194631f8727382113cdefec49fc8cc09/app/src/main/java/com/golddog/mask_location/ui/adapter/CitiesAdapter.kt#L19-L25)
현재는 직접 updateItem을 구현하는 번거로움이 존재하지만 ListAdapter는 그런 부분을 해결할 수 있습니다.

[관련 링크 AndroidDeveloper - ListAdapter](https://developer.android.com/reference/android/support/v7/recyclerview/extensions/ListAdapter)
 한번 검토해주세용

**Comment by KRMKGOLD** [comment]
처음 액티비티 실행 후 다시 갱신되는 로직이 하나도 존재하지 않기 때문에 DiffUtil 사용은 하지 않았습니다. Close합니다.
