### ISSUE TITLE
Naver map URL Scheme Issue

### ISSUE THREAD

**Issue by choi-seung-min** [Team-DA/Corona-Solution#67]
![image](https://app.gitkraken.com/api/glo/boards/5e67e57597faeb0011ad6047/attachments/5eb6b7294435d10014b8d02c)

**Comment by choi-seung-min** [comment]
https://docs.ncloud.com/ko/naveropenapi_v3/maps/url-scheme/url-scheme.html
네이버맵 공식 문서의 예제를 참고했으며 application id는 gradle에서 가져왔습니다.
사진에 첨부한 것은 URL Scheme을 설정하고 버튼을 클릭했을 때의 에러 로그입니다.

**Comment by KRMKGOLD** [comment]
저 오류 발생은 네이버 지도가 없을 때 발생하는 오류였음, 직접 작업해 플레이스토어로 넘기는 로직을 추가했고 현재 (2020-05-11 PM 08:35) 기준으로 seongha-dev에 추가되어 있음. master에 PR된 이후에 Close하겠음
